import os
import json
from datetime import datetime, timezone
from typing import Dict, Any
from app.research_os.governance.dataset_registry import QUALITY_REPORTS_DIR, ensure_research_storage_structure


class QualityReporter:
    """Compiles and stores Data Quality Audit Reports for every export operation."""

    def __init__(self):
        ensure_research_storage_structure()

    def generate_report(
        self,
        dataset_id: str,
        expected_rows: int,
        actual_rows: int,
        duplicate_snapshots: int = 0,
        missing_minutes_count: int = 0,
        missing_strikes_count: int = 0,
        null_pcr_count: int = 0,
        null_iv_count: int = 0,
        corrupt_rows_count: int = 0,
        sha256_verification: bool = True,
    ) -> Dict[str, Any]:
        """Compiles quality metrics and outputs JSON + Markdown quality reports."""
        
        # Quality Pass Criteria: Zero corrupt rows, row count match, and valid SHA256
        quality_pass = (
            corrupt_rows_count == 0
            and actual_rows >= expected_rows
            and sha256_verification
            and duplicate_snapshots == 0
        )

        timestamp_iso = datetime.now(timezone.utc).isoformat()
        report_id = f"QR-{dataset_id}"

        report_data = {
            "report_id": report_id,
            "dataset_id": dataset_id,
            "export_date": timestamp_iso,
            "expected_rows": expected_rows,
            "actual_rows": actual_rows,
            "duplicate_snapshots": duplicate_snapshots,
            "missing_minutes_count": missing_minutes_count,
            "missing_strikes_count": missing_strikes_count,
            "null_pcr_count": null_pcr_count,
            "null_iv_count": null_iv_count,
            "corrupt_rows_count": corrupt_rows_count,
            "sha256_verification": sha256_verification,
            "quality_pass": quality_pass,
            "status": "PASS" if quality_pass else "FAIL",
        }

        # 1. Save JSON report
        json_path = os.path.join(QUALITY_REPORTS_DIR, f"{report_id}.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=2)

        # 2. Save Markdown human-readable report
        md_path = os.path.join(QUALITY_REPORTS_DIR, f"{report_id}.md")
        md_content = self._render_markdown(report_data)
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        report_data["json_path"] = json_path
        report_data["md_path"] = md_path
        return report_data

    def _render_markdown(self, data: Dict[str, Any]) -> str:
        status_badge = "🟢 PASS" if data["quality_pass"] else "🔴 FAIL"
        return f"""# Data Quality Audit Report — {data['report_id']}

- **Dataset ID**: `{data['dataset_id']}`
- **Export Date (UTC)**: `{data['export_date']}`
- **Quality Status**: {status_badge}

## Audit Metrics

| Metric | Recorded Value | Target Standard | Status |
| :--- | :--- | :--- | :--- |
| **Expected Rows** | {data['expected_rows']} | N/A | Info |
| **Actual Exported Rows** | {data['actual_rows']} | == Expected | {'✅' if data['actual_rows'] >= data['expected_rows'] else '❌'} |
| **Duplicate Snapshots** | {data['duplicate_snapshots']} | 0 | {'✅' if data['duplicate_snapshots'] == 0 else '❌'} |
| **Corrupt Rows** | {data['corrupt_rows_count']} | 0 | {'✅' if data['corrupt_rows_count'] == 0 else '❌'} |
| **Missing Minutes Gaps** | {data['missing_minutes_count']} | 0 | {'✅' if data['missing_minutes_count'] == 0 else '⚠️'} |
| **Missing Strikes Count** | {data['missing_strikes_count']} | 0 | {'✅' if data['missing_strikes_count'] == 0 else '⚠️'} |
| **Null PCR Records** | {data['null_pcr_count']} | 0 | {'✅' if data['null_pcr_count'] == 0 else '⚠️'} |
| **Null IV Records** | {data['null_iv_count']} | 0 | {'✅' if data['null_iv_count'] == 0 else '⚠️'} |
| **SHA256 Verification** | {data['sha256_verification']} | True | {'✅' if data['sha256_verification'] else '❌'} |

---
*Generated by OI Lens Research OS QualityReporter (ETL-v1.0.0)*
"""
